### PR TITLE
convert from console.log -> standard logging

### PR DESCRIPTION
**Pull request by indirectlylit**
addresses:

```
    WARNING in ../perseus/exercise_perseus_render/assets/src/vue/index.vue
    
    /Users/d/Projects/learning_equality/repos/perseus/exercise_perseus_render/assets/src/vue/index.vue
       92:13  warning  Unexpected console statement  no-console
      125:11  warning  Unexpected console statement  no-console
    
    ✖ 2 problems (0 errors, 2 warnings)
```

### CODE REVIEW

**Comment by indirectlylit** [comment]
We may also want to look at handling these errors rather than just logging them?

**Comment by 66eli77** [comment]
thanks

**Comment by indirectlylit** [comment]
I didn't bother pushing to pypi - maybe wait until the next change because this is kind of trivial

**Comment by 66eli77** [comment]
sounds good to me.

**Pull request merged**
