### PR TITLE
remove dependence on core themes

### PR DESCRIPTION
**Pull request by indirectlylit**
wasn't actually necessary

### CODE REVIEW

**Review by rtibbles — APPROVED** [review]

**Comment by indirectlylit** [comment]
would you mind releasing this as 1.1.6 and i'll include an upgrade in my kolibri PR?

**Comment by rtibbles** [comment]
Can do - are we releasing any new languages with 0.12.4?

**Comment by indirectlylit** [comment]
no, we're not

**Comment by rtibbles** [comment]
Not even Korean?

**Pull request merged**
