### PR TITLE
Large Text Render Fix

### PR DESCRIPTION
**Pull request by DXCanas**
Haven't tested extensively, so maybe considered WIP. Looks like there are some styles missing from the perseus plugin that would do us a lot of good. I actually went over to KA's site to see what we weren't getting.

Maybe fixes https://github.com/learningequality/kolibri/issues/1329

### CODE REVIEW

**Comment by indirectlylit** [comment]
we shouldn't target PRs to master - retargeting to 0.4.x

**Comment by indirectlylit** [comment]
whoops - wrong repo

**Comment by rtibbles** [comment]
We also shouldn't target to master here too. 0.6.x.

**Comment by rtibbles** [comment]
(this will also rectify my accidentally merging @christianmemije's PR to master)

**Pull request merged**
