### PR TITLE
Updated strings with Italian translation

### PR DESCRIPTION
**Pull request by radinamatic**
All translation for Italian plus a few corrected strings in French.

cc @jonboiser @indirectlylit

### CODE REVIEW

**Comment by jonboiser** [comment]
Looks good to me. I wonder why this is the first time the CSV files. were created.

**Comment by indirectlylit** [comment]
@nucleogenesis do you know the answer to this? I forget whether we support context in perseus or not

**Comment by nucleogenesis** [comment]
I just made a PR https://github.com/radinamatic/kolibri-exercise-perseus-plugin/pull/1 at Radina's fork to this branch that removes the CSV_FILES. Those are ignored in Kolibri's `gitignore` so I did that here as well.

I initially also added the `en` files to the `gitignore` because Kolibri has it that way - but that wasn't done previously here so I figure it's safest to leave as-is.

@radinamatic if you merge that PR you can then it should automatically reflect here - if you need to do more work locally for any reason run `git fetch --all` first to update your local code with the changes from that PR (after it's merged).

@indirectlylit or @jonboiser could you give that PR a quick look?

**Comment by indirectlylit** [comment]
thanks, looks good

> I initially also added the en files to the gitignore because Kolibri has it that way - but that wasn't done previously here so I figure it's safest to leave as-is.

Agreed ignoring seems more correct, but safe to leave as-is

**Pull request merged**
